spring:
  datasource:
    url: jdbc:postgresql://centerbeam.proxy.rlwy.net:44655/railway
    username: postgres
    password: GvDdQbfGuGUIkuBYomXAVzXrObZoIAUA
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

cloudinary:
  cloud-name: dkloakzs6
  api-key: 162361396439147
  api-secret: DVu7SNnY50pVCr7xxY1mRmsO4Os
