spring:
  datasource:
    url: jdbc:postgresql://nozomi.proxy.rlwy.net:53576/railway
    username: postgres
    password: mvfqlmRhNlfxyluSuiIiEJWlBylcPrwT
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
      enabled: true
      location: ${java.io.tmpdir}
      file-size-threshold: 0

server:
  tomcat:
    max-http-form-post-size: 20MB
    max-swallow-size: 20MB
    max-connections: 200
    threads:
      max: 200
    max-http-post-size: 20971520
    max-parameter-count: 10000
  max-http-header-size: 20MB

logging:
  level:
    org.springframework.web.multipart: DEBUG
    org.apache.commons.fileupload: DEBUG
    org.apache.catalina: DEBUG
    org.apache.tomcat: DEBUG
    org.apache.coyote.http11: DEBUG


cloudinary:
  cloud-name: dkloakzs6
  api-key: 162361396439147
  api-secret: DVu7SNnY50pVCr7xxY1mRmsO4Os

